version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-2:637423528516:task-definition/blue-green-test:1"
        LoadBalancerInfo:
          ContainerName: "app"
          ContainerPort: 3000
        PlatformVersion: "LATEST"
        NetworkConfiguration:
          AwsvpcConfiguration:
            AssignPublicIp: "ENABLED"
            Subnets: ["subnet-0cad12f46ff9160e6", "subnet-00b346284fccb1bab"]
            SecurityGroups: ["sg-04e823108a9b41d93"]